blank_issues_enabled: true
contact_links:
  - name: â“ Questions
    url: https://github.com/cobbler/cobbler/discussions
    about: Ask questions here
  - name: ğŸ’¬ Gitter Chat
    url: https://gitter.im/cobbler/community
    about: Chat with the Cobbler community
